apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  POSTGRES_USER_AUTH_DB: "postgres"
  POSTGRES_PASSWORD_AUTH_DB: "postgres"
  POSTGRES_DB_AUTH_DB: "AUTH_DB"

  POSTGRES_USER_IMAGE_DB: "postgres"
  POSTGRES_PASSWORD_IMAGE_DB: "postgres"
  POSTGRES_DB_IMAGE_DB: "IMAGE_DB"

  MONGO_USERNAME: "dbuser"
  MONGO_PASSWORD: "dbpassword"
  MONGO_DB_NAME: "activitydb"

  JWT_SECRET: "8P8T8NicYwGrAKzXH4LnGFeORizRrKklDJun3bXVEnw"
  GATEWAY_HEADER: "secret-header-gt"

  MAIL_HOST_TMP: "smtp.gmail.com"
  MAIL_POST_TMP: "587"
  MAIL_USERNAME_TMP: "ddjj676dd@gmail.com"
  MAIL_PASSWORD_TMP: "tsgh crmm keht cgcb"

  AWS_SECRET_KEY: "secretkey"
  AWS_ACCESS_KEY: "accesskey"
