apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: hilt0n3/auth-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB_AUTH_DB
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://auth-user-db.app.svc.cluster.local:5432/$(POSTGRES_DB_AUTH_DB)"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER_AUTH_DB
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD_AUTH_DB

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_HOST_TMP
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_USERNAME_TMP
            - name: MAIL_POST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_POST_TMP
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MAIL_PASSWORD_TMP

            - name: FRONTEND_URL_CORS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_URL_CORS
